<a href="https://colab.research.google.com/github/Moksh45/Machine-Learning-Code/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [1]:
import numpy as np

In [7]:
my_list = [1,2,3,4,5]
arr=np.array(my_list)
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [8]:
arr.shape   #1D array


(5,)

In [14]:
#Creating 2D array
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]
arr = np.array([my_list1,my_list2,my_list3])
print (arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
arr.shape # Know it is 2D Array

(3, 5)

In [17]:
arr.reshape(5,3)    # reshape will help you to reshape you array 5 is number of row and 3 is number of column

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# **Indexing**

In [18]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])   #indexing start from 0 this 

In [20]:
arr1[3]

4

In [24]:
arr[0:2,0:2] #indexing in 2D array

array([[1, 2],
       [6, 7]])

In [28]:
arr[:,3:5]

array([[ 4,  5],
       [ 9, 10],
       [14, 15]])

In [37]:
arr2=np.arange(0,10)   #make array and element are from 0 to 9
arr3=np.arange(0,10)

In [33]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr2=np.arange(0,10,2)   #start , end , step
arr3=np.arange(0,10, step=2) #both are same

In [40]:
print(arr2)
print(arr3)


[0 2 4 6 8]
[0 2 4 6 8]


In [46]:
arr4 = np.linspace(1,10,50)   # give 50 point between 1 to 10
arr4

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [48]:
#copy function and broadcasting
print(arr3)

arr4[3:]=100
print(arr4)

[  0   2   4 100 100]
[  1.           1.18367347   1.36734694 100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.        ]
