<a href="https://colab.research.google.com/github/Moksh45/Machine-Learning-Code/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd
import numpy as np

In [3]:
 ## Playing With Dataframe
 df=pd.DataFrame(np.arange(0,20).reshape(5,4),index = ['Row1','Row2','Row3','Row4','Row5'],columns=['columns1','columns2','columns3','columns4'])

In [4]:
df.head()

columns1  columns2  columns3  columns4
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [5]:
df.to_csv('Test1.csv') #use to convert data into excel not work in colab using in jupyter nootbook

In [6]:
## Accessing the Element
type(df.loc['Row1'])  #type is arrray or pandas.core.series.Series
df.loc['Row1']

columns1    0
columns2    1
columns3    2
columns4    3
Name: Row1, dtype: int64

In [7]:
df.iloc[0:2,0:2]  #type is DataFrame

columns1  columns2
Row1         0         1
Row2         4         5

In [8]:
#convert dataframe into array
print(df.iloc[:,1:].values,"\n\n")
print(df.iloc[:,1:].values.shape)


[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]] 


(5, 3)


In [9]:
df['columns1'].value_counts()  #show count of each value

0     1
4     1
8     1
12    1
16    1
Name: columns1, dtype: int64

In [10]:
df['columns1'].unique() ## show all unique Value

array([ 0,  4,  8, 12, 16])

In [11]:
df[['columns1','columns2']]

columns1  columns2
Row1         0         1
Row2         4         5
Row3         8         9
Row4        12        13
Row5        16        17

In [19]:
path = "/content/drive/MyDrive/Colab CSV File/train.csv"
df = pd.read_csv(path,sep=",")

In [20]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [16]:
df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [23]:
#Get the unique category counts
df['X0'].value_counts()   #to find different number of category

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: X0, dtype: int64

In [24]:
df['y']>100

0        True
1       False
2       False
3       False
4       False
        ...  
4204     True
4205     True
4206     True
4207    False
4208     True
Name: y, Length: 4209, dtype: bool

In [25]:
df[df['y']>100]

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al  r   e  f  d   f  h  s  ...     0     0     0     0   
8       27  108.67   w  s  as  e  d   f  i  h  ...     1     0     0     0   
9       30  126.99   j  b  aq  c  d   f  a  e  ...     0     0     1     0   
10      31  102.09   h  r   r  f  d   f  h  p  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4202  8402  123.34  ap  l   s  c  d  aa  d  r  ...     0     0     0     0   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
8        0     0     0     0     0     0  
9        0     0     0     0     0     0  
10       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4202     0     0     0     0     0     0  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[2004 rows x 378 columns]

# **CSV**

In [26]:
from io import StringIO,BytesIO

In [27]:
data = ('col1,col2,col3\n'
'x,y,1\n'
'a,b,2\n'
'c,d,3\n')

In [28]:
type(data)

str

In [29]:
pd.read_csv(StringIO(data))   #use to change str to csv file

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [35]:
## Read from Specific Columns
df=pd.read_csv(StringIO(data),usecols = ['col1','col3'])

In [36]:
df

col1  col3
0    x     1
1    a     2
2    c     3

In [37]:
 df.to_csv('test.csv') # use to save this as csv file

In [63]:
#specifying column data type
data=('a,b,c,d\n'
      '1,2,3,4\n'
      '5,6,7,8\n'
      '9,10,11,12')

In [43]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11


In [55]:
df=pd.read_csv(StringIO(data),dtype = object)

In [56]:
type(df['a'][1])

str

In [57]:
df

a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [64]:
#for give each column different data type use this 
df=pd.read_csv(StringIO(data),dtype={'b':int,'c':np.float,'d':int})

<ipython-input-64-6a9bfd310d66>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  df=pd.read_csv(StringIO(data),dtype={'b':int,'c':np.float,'d':int})


In [65]:
df

a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

In [67]:
# index columns and training delimiters
data= ('index,a,b,c\n'
'4,apple,bat,5.7\n'
'8,orange,cow,10')

In [74]:
pd.read_csv(StringIO(data),index_col=0)    # use for making 4 and 8 as a index col


a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [75]:
data= ('a,b,c\n'
'4,apple,bat,5.7\n'
'8,orange,cow,10')

In [79]:
pd.read_csv(StringIO(data),index_col=False) 

/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  return func(*args, **kwargs)


a       b    c
0  4   apple  bat
1  8  orange  cow

In [80]:
#combining usecols and index_col
data= ('a,b,c\n'
'4,apple,bat,5.7\n'
'8,orange,cow,10')

In [81]:
pd.read_csv(StringIO(data),usecols=['b','c'],index_col=False) 

b    c
0   apple  bat
1  orange  cow

In [82]:
## Quoting and Escape Characters usefull in NLP
data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [83]:
pd.read_csv(StringIO(data),escapechar='\\') 

a  b
0  hello, "Bob", nice to see you  5

# **Read Json To CSV**

In [93]:
#json data is like key value pair
data1 = '{"emp_name":"John","email":"Khatarnakkumar@gmail.com","job_profile":[{"Title":"Tema Lead","Title2":"Devloper"}]}'
df1 = pd.read_json(data1)

In [94]:
#convert json to csv
df.to_csv('wine.csv')

In [96]:
df1

emp_name                     email  \
0     John  Khatarnakkumar@gmail.com   

                                    job_profile  
0  {'Title': 'Tema Lead', 'Title2': 'Devloper'}

In [95]:
df1.to_json()

'{"emp_name":{"0":"John"},"email":{"0":"Khatarnakkumar@gmail.com"},"job_profile":{"0":{"Title":"Tema Lead","Title2":"Devloper"}}}'

In [99]:
#convert json to different json formats
df1.to_json(orient="records")

'[{"emp_name":"John","email":"Khatarnakkumar@gmail.com","job_profile":{"Title":"Tema Lead","Title2":"Devloper"}}]'

# **Reading HTML content**

In [105]:
url = "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list"
dfs = pd.read_html(url)


In [107]:
dfs[0]

Bank NameBank           CityCity StateSt  CertCert  \
0                    Almena State Bank             Almena      KS     15426   
1           First City Bank of Florida  Fort Walton Beach      FL     16748   
2                 The First State Bank      Barboursville      WV     14361   
3                   Ericson State Bank            Ericson      NE     18265   
4     City National Bank of New Jersey             Newark      NJ     21111   
..                                 ...                ...     ...       ...   
558                 Superior Bank, FSB           Hinsdale      IL     32646   
559                Malta National Bank              Malta      OH      6629   
560    First Alliance Bank & Trust Co.         Manchester      NH     34264   
561  National State Bank of Metropolis         Metropolis      IL      3815   
562                   Bank of Honolulu           Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0                            Equity Bank    October 23, 2020     10538  
1              United Fidelity Bank, fsb    October 16, 2020     10537  
2                         MVB Bank, Inc.       April 3, 2020     10536  
3             Farmers and Merchants Bank   February 14, 2020     10535  
4                        Industrial Bank    November 1, 2019     10534  
..                                   ...                 ...       ...  
558                Superior Federal, FSB       July 27, 2001      6004  
559                    North Valley Bank         May 3, 2001      4648  
560  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
561              Banterra Bank of Marion   December 14, 2000      4646  
562                   Bank of the Orient    October 13, 2000      4645  

[563 rows x 7 columns]

In [112]:
url1 = "https://en.wikipedia.org/wiki/Mobile_country_code"
dfs1 = pd.read_html(url1,match='Country',header = 0)

In [114]:
dfs1[0]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

# **Readin Excel File**

In [ ]:
# df_excel=pd.read_excel("file name")
# df_excel.head()