<a href="https://colab.research.google.com/github/Moksh45/Machine-Learning-Code/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [5]:
 ## Playing With Dataframe
 df=pd.DataFrame(np.arange(0,20).reshape(5,4),index = ['Row1','Row2','Row3','Row4','Row5'],columns=['columns1','columns2','columns3','columns4'])

In [10]:
df.head()

columns1  columns2  columns3  columns4
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [11]:
df.to_csv('Test1.csv') #use to convert data into excel not work in colab using in jupyter nootbook

In [15]:
## Accessing the Element
type(df.loc['Row1'])  #type is arrray or pandas.core.series.Series
df.loc['Row1']

columns1    0
columns2    1
columns3    2
columns4    3
Name: Row1, dtype: int64

In [13]:
df.iloc[0:2,0:2]  #type is DataFrame

columns1  columns2
Row1         0         1
Row2         4         5

In [18]:
#convert dataframe into array
print(df.iloc[:,1:].values,"\n\n")
print(df.iloc[:,1:].values.shape)


[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]] 


(5, 3)


In [19]:
df['columns1'].value_counts()  #show count of each value

0     1
4     1
8     1
12    1
16    1
Name: columns1, dtype: int64

In [20]:
df['columns1'].unique() ## show all unique Value

array([ 0,  4,  8, 12, 16])

In [21]:
df[['columns1','columns2']]

columns1  columns2
Row1         0         1
Row2         4         5
Row3         8         9
Row4        12        13
Row5        16        17