<a href="https://colab.research.google.com/github/Moksh45/Machine-Learning-Code/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd
import numpy as np

In [3]:
 ## Playing With Dataframe
 df=pd.DataFrame(np.arange(0,20).reshape(5,4),index = ['Row1','Row2','Row3','Row4','Row5'],columns=['columns1','columns2','columns3','columns4'])

In [4]:
df.head()

columns1  columns2  columns3  columns4
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [5]:
df.to_csv('Test1.csv') #use to convert data into excel not work in colab using in jupyter nootbook

In [6]:
## Accessing the Element
type(df.loc['Row1'])  #type is arrray or pandas.core.series.Series
df.loc['Row1']

columns1    0
columns2    1
columns3    2
columns4    3
Name: Row1, dtype: int64

In [7]:
df.iloc[0:2,0:2]  #type is DataFrame

columns1  columns2
Row1         0         1
Row2         4         5

In [8]:
#convert dataframe into array
print(df.iloc[:,1:].values,"\n\n")
print(df.iloc[:,1:].values.shape)


[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]] 


(5, 3)


In [9]:
df['columns1'].value_counts()  #show count of each value

0     1
4     1
8     1
12    1
16    1
Name: columns1, dtype: int64

In [10]:
df['columns1'].unique() ## show all unique Value

array([ 0,  4,  8, 12, 16])

In [11]:
df[['columns1','columns2']]

columns1  columns2
Row1         0         1
Row2         4         5
Row3         8         9
Row4        12        13
Row5        16        17

In [19]:
path = "/content/drive/MyDrive/Colab CSV File/train.csv"
df = pd.read_csv(path,sep=",")

In [20]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [16]:
df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [23]:
#Get the unique category counts
df['X0'].value_counts()   #to find different number of category

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: X0, dtype: int64

In [24]:
df['y']>100

0        True
1       False
2       False
3       False
4       False
        ...  
4204     True
4205     True
4206     True
4207    False
4208     True
Name: y, Length: 4209, dtype: bool

In [25]:
df[df['y']>100]

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al  r   e  f  d   f  h  s  ...     0     0     0     0   
8       27  108.67   w  s  as  e  d   f  i  h  ...     1     0     0     0   
9       30  126.99   j  b  aq  c  d   f  a  e  ...     0     0     1     0   
10      31  102.09   h  r   r  f  d   f  h  p  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4202  8402  123.34  ap  l   s  c  d  aa  d  r  ...     0     0     0     0   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
8        0     0     0     0     0     0  
9        0     0     0     0     0     0  
10       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4202     0     0     0     0     0     0  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[2004 rows x 378 columns]

# **CSV**

In [26]:
from io import StringIO,BytesIO

In [27]:
data = ('col1,col2,col3\n'
'x,y,1\n'
'a,b,2\n'
'c,d,3\n')

In [28]:
type(data)

str

In [29]:
pd.read_csv(StringIO(data))   #use to change str to csv file

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [35]:
## Read from Specific Columns
df=pd.read_csv(StringIO(data),usecols = ['col1','col3'])

In [36]:
df

col1  col3
0    x     1
1    a     2
2    c     3

In [37]:
 df.to_csv('test.csv') # use to save this as csv file

In [63]:
#specifying column data type
data=('a,b,c,d\n'
      '1,2,3,4\n'
      '5,6,7,8\n'
      '9,10,11,12')

In [43]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11


In [55]:
df=pd.read_csv(StringIO(data),dtype = object)

In [56]:
type(df['a'][1])

str

In [57]:
df

a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [64]:
#for give each column different data type use this 
df=pd.read_csv(StringIO(data),dtype={'b':int,'c':np.float,'d':int})

<ipython-input-64-6a9bfd310d66>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  df=pd.read_csv(StringIO(data),dtype={'b':int,'c':np.float,'d':int})


In [65]:
df

a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12